# Write your code here :-)
print("+=====================+")
print("|  BEST FRIEND MAKER  |")
print("=======================")
print("")
print("Hi, I'm the computer.")
print('')
name = input("What is your name? ")
if name == "Creeper":
    print('Aww man')
print('')
color = input("Hi, " + name + "! What is your favorite color? ")
print('My favorite color is ' + color + ' too!')
print('')
movie = input('What is your favorite movie? ')
print("What!?! My favorite movie is also " + movie + "!")
print('')
game = input("What is your favorite game? ")
print("Get out of here, " + name + "! My favorite game is " + game + " too!")
print("")
print('We like the same things! We should be best friends!')

